Update to Python 3.10 and rocm-docs-core 1.1.1 (#218)
* Update to Python 3.10 and rocm-docs-core 1.1.1

* Remove get_html_templates_path() in templates_path

To fix exception

Exception: Found the path from `ablog.get_html_templates_path()` in the `templates_path` variable from `conf.py`. Doing so interferes with Ablog's ability to stay compatible with Sphinx themes that support it out of the box. Please remove `get_html_templates_path` from `templates_path` in your `conf.py` to resolve this.